image: maven:3.9.1-openjdk-11

pipelines:
  branches:
    master:
      - step:
          caches:
            - maven
          script:
            - mvn -B -DskipTests -Pit.tidalwave-ci-v1,generate-revision-id
