spring:
  datasource:
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      format_sql: false
    properties:
      hibernate:
        show_sql: false
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect

logging:
  level:
    org.hibernate: INFO
